### ISSUE TITLE
请确认您站点的可访问性（DNS问题）

### ISSUE THREAD

**Issue by HelimLee** [Big-Cake-jpg/big-cake-jpg.github.io#104]
朋友您好！您的网站（域名lihaoyu.cn）现在无法打开。请您核实是否正确配置DNS，或是否给域名续期。下面是您的域名的DNS解析结果和WHOIS查询结果。

![image](https://github.com/Big-Cake-jpg/big-cake-jpg.github.io/assets/56996853/737773e9-b28a-4571-914b-e85c5d9bc523)

![image](https://github.com/Big-Cake-jpg/big-cake-jpg.github.io/assets/56996853/4ecda725-26a2-45ae-9423-d14d0ff917de)

![image](https://github.com/Big-Cake-jpg/big-cake-jpg.github.io/assets/56996853/7cb172a2-1902-4fe8-af98-b6bacab136bc)

**Comment by Big-Cake-jpg** [comment]
哦 不好意思 当时没有通知到您。

非常抱歉，目前 `lihaoyu.cn` 正在进行 ICP 备案，应相关法律法规要求暂时关闭，预计 8 月 10 日后恢复正常访问。

如果您有需要，可以将链接替换为 `bigcake-blog.netlify.app`。

给您造成不便，敬请谅解。
