### ISSUE TITLE
申请友链链接

### ISSUE THREAD

**Issue by Autuan** [Big-Cake-jpg/big-cake-jpg.github.io#225]
博主  您好

希望我们能在站点互加友情链接

我的站点地址为 `https://autuan.top`

您的站点 `https://www.lihaoyu.cn/`  我已加入我的友链了 

:)

**Comment by gxres042** [comment]
> 博主  您好
> 
> 希望我们能在站点互加友情链接
> 
> 我的站点地址为 `https://autuan.top`
> 
> 您的站点 `https://www.lihaoyu.cn/`  我已加入我的友链了 
> 
> :)

你应该去 friend-links 仓库按步骤操作 :)
